### PR TITLE
Fix Authorization header usage in code examples

### LINKED ISSUE #42: Authorization not working with this code
I kept getting HTTP 401 responses from this:
const res = http.get("http://http.example.com", { Authorization: session });
Changing it to 
const res = http.get("http://http.example.com", {"headers": {"Authorization": session }});
fixed the issue

### PR DESCRIPTION
**Pull request by specter96**
Changes _Authorization_  header to be nested in the http GET request.

Closes #42

### CODE REVIEW

**Review by joanlopez — APPROVED** [review]

**Comment by joanlopez** [comment]
Hey @specter96, could you please review and sign the CLA, please? Thanks! 🙏🏻

**Comment by specter96** [comment]
Hey @joanlopez, just did so. Don't know how long it takes to register :)

Screenshot 2024-09-02 at 11 51 11

**Comment by joanlopez** [comment]
> **Theus, Vincent** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).



> Hey @joanlopez, just did so. Don't know how long it takes to register :)

Hey @specter96,

Taking a look at the CLA bot message, it says:

_> **Theus, Vincent** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)._

So, perhaps you need to amend the commit author? Can you check email address matches with your account, please?

Thanks!

**Comment by specter96** [comment]
@joanlopez thanks for merging this and sorry about the issues with the CLA

**Comment by joanlopez** [comment]
> @joanlopez thanks for merging this and sorry about the issues with the CLA

Don't worry, and thanks to you for reporting it and fixing it! 🙇🏻

**Pull request merged**
